name: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:11.0.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Import gpg key
        run: |
          echo ${{ secrets.GPG_BASE64_KEY }} | base64 -d > ./private.key
          gpg --import --passphrase ${{ secrets.GPG_PASSPHRASE }} --batch --yes ./private.key
          rm -f ./private.key

      - name: Deploy
        run: |
          mvn --settings m2/settings.xml deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: central-bundle
          path: ${{ github.workspace }}/target/central-publishing/central-bundle.zip
      

